In [64]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [65]:
from pylab import rcParams

In [66]:
data = pd.read_csv("creditcard.csv")

In [67]:
data.columns

Index(['Time', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10',
       'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20',
       'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'Amount',
       'Class'],
      dtype='object')

In [68]:
x = data[['V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10',
       'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20',
       'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'Amount',]]

In [69]:
y = data['Class']

In [70]:
from sklearn.model_selection import train_test_split

In [71]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [72]:
print(x_train.shape,x_test.shape)

(227845, 29) (56962, 29)


In [73]:
from sklearn.ensemble import GradientBoostingClassifier

In [74]:
import xgboost as xgb

In [75]:
dtrain = xgb.DMatrix(x_train,label=y_train)

In [76]:
dtest = xgb.DMatrix(x_test)

In [153]:
#set Parameters
parameters={'max_depth':15, 'eta':1, 'silent':1,'objective':'binary:logistic','eval_metric':'auc','learning_rate':.05}

In [154]:
rounds = 300
xg = xgb.train(parameters, dtrain, rounds)

c:\Users\Ronak\AppData\Local\Programs\Python\Python312\Lib\site-packages\xgboost\core.py:160: UserWarning: [14:13:41] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0b3782d1791676daf-1\xgboost\xgboost-ci-windows\src\learner.cc:742: 
Parameters: { "silent" } are not used.

  warnings.warn(smsg, UserWarning)


In [155]:
y_predict = xg.predict(dtest)

In [156]:
y_predict

array([9.9643195e-01, 5.3461185e-06, 1.7936351e-05, ..., 4.3248252e-05,
       5.5768978e-06, 1.8443937e-04], dtype=float32)

In [157]:
y_predict>=0.5

array([ True, False, False, ..., False, False, False])

In [158]:
y_predict[y_predict>=0.5] = 1

In [159]:
y_predict

array([1.0000000e+00, 5.3461185e-06, 1.7936351e-05, ..., 4.3248252e-05,
       5.5768978e-06, 1.8443937e-04], dtype=float32)

In [160]:
y_predict[y_predict<0.5] = 0

In [161]:
y_predict

array([1., 0., 0., ..., 0., 0., 0.], dtype=float32)

In [162]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [164]:
print(confusion_matrix(y_test,y_predict))
print(classification_report(y_test, y_predict))
print(accuracy_score(y_test, y_predict))

[[56861     3]
 [   20    78]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56864
           1       0.96      0.80      0.87        98

    accuracy                           1.00     56962
   macro avg       0.98      0.90      0.94     56962
weighted avg       1.00      1.00      1.00     56962

0.9995962220427653
